update troubleshooting for Flink 1.12
ververica/flink-training pull request #12
Opened 2021-03-17 11:18 UTC by alpinegizmo

I have

* removed TimeCharacteristic
* stopped using timeWindow
* rebased and included the commit from https://github.com/ververica/flink-training/pull/2 that reworks the troubled streaming job solutions to use WatermarkStrategy

2021-03-17 15:19 UTC, NicoK requested changes
Thanks for these updates, I also ran the troubled streaming job in our troubleshooting test VM with VVP 2.4 and it shows roughly the same numbers in this quick test.

Can you add two more things?

1. update to 1.12.2
2. remove the remaining `env.setStreamTimeCharacteristic(TimeCharacteristic.EventTime)` in some of the scala exercises/solutions (hourly tips + long rides - so this should probably go into apache/flink-training as well)

2021-03-17 15:19 UTC, NicoK commented on build.gradle
> +        flinkVersion = '1.12.0'
let's increase that to 1.12.2 while we're changing it
```suggestion
        flinkVersion = '1.12.2'
```

2021-03-18 09:16 UTC, alpinegizmo commented
The time characteristic was already removed from the scala exercises and solutions. Perhaps you are just noticing what's in the bin directories.

2021-03-18 10:03 UTC, NicoK approved these changes
Thanks @alpinegizmo, you were right - I still had some bin directories that `gradlew clean` didn't clean up

2021-03-18 10:43 UTC, merged